// Subscription provider catalog used by the dedicated Subscriptions capture flow.
export const subscriptionProviderGroups = [
  { id: 'streaming', label: 'Streaming' },
  { id: 'music', label: 'Music' },
  { id: 'tech', label: 'Tech / Software' },
  { id: 'gaming', label: 'Gaming' },
  { id: 'other', label: 'Other' },
]

// Prices are quick-entry hints only. Users can always choose OTHER for real-world variations.
export const subscriptionProviders = [
  {
    id: 'netflix',
    label: 'Netflix',
    group: 'streaming',
    icon: 'movie',
    priceOptions: [7.99, 13.99, 19.99],
  },
  {
    id: 'prime-video',
    label: 'Prime Video',
    group: 'streaming',
    icon: 'movie',
    priceOptions: [4.99, 8.99, 14.99],
  },
  {
    id: 'disney-plus',
    label: 'Disney+',
    group: 'streaming',
    icon: 'live_tv',
    priceOptions: [8.99, 11.99, 13.99],
  },
  {
    id: 'max',
    label: 'Max',
    group: 'streaming',
    icon: 'live_tv',
    priceOptions: [9.99, 13.99, 19.99],
  },
  {
    id: 'apple-tv-plus',
    label: 'Apple TV+',
    group: 'streaming',
    icon: 'tv',
    priceOptions: [6.99, 9.99, 12.99],
  },
  {
    id: 'filmin',
    label: 'Filmin',
    group: 'streaming',
    icon: 'theaters',
    priceOptions: [7.99, 9.99, 14.99],
  },
  {
    id: 'spotify',
    label: 'Spotify',
    group: 'music',
    icon: 'music_note',
    priceOptions: [5.99, 10.99, 17.99],
  },
  {
    id: 'apple-music',
    label: 'Apple Music',
    group: 'music',
    icon: 'album',
    priceOptions: [5.99, 10.99, 16.99],
  },
  {
    id: 'youtube-music',
    label: 'YouTube Music',
    group: 'music',
    icon: 'headphones',
    priceOptions: [5.99, 10.99, 16.99],
  },
  {
    id: 'tidal',
    label: 'Tidal',
    group: 'music',
    icon: 'graphic_eq',
    priceOptions: [5.99, 10.99, 16.99],
  },
  {
    id: 'youtube-premium',
    label: 'YouTube Premium',
    group: 'tech',
    icon: 'smart_display',
    priceOptions: [8.99, 13.99, 25.99],
  },
  {
    id: 'icloud-plus',
    label: 'iCloud+',
    group: 'tech',
    icon: 'cloud',
    priceOptions: [0.99, 2.99, 9.99],
  },
  {
    id: 'google-one',
    label: 'Google One',
    group: 'tech',
    icon: 'cloud_queue',
    priceOptions: [1.99, 2.99, 9.99],
  },
  {
    id: 'dropbox',
    label: 'Dropbox',
    group: 'tech',
    icon: 'folder',
    priceOptions: [9.99, 11.99, 19.99],
  },
  {
    id: 'microsoft-365',
    label: 'Microsoft 365',
    group: 'tech',
    icon: 'work',
    priceOptions: [6.99, 9.99, 12.99],
  },
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    group: 'tech',
    icon: 'psychology',
    priceOptions: [20, 25, 200],
  },
  {
    id: 'claude',
    label: 'Claude',
    group: 'tech',
    icon: 'auto_awesome',
    priceOptions: [20, 25, 200],
  },
  {
    id: 'playstation-plus',
    label: 'PlayStation Plus',
    group: 'gaming',
    icon: 'sports_esports',
    priceOptions: [8.99, 13.99, 16.99],
  },
  {
    id: 'xbox-game-pass',
    label: 'Xbox Game Pass',
    group: 'gaming',
    icon: 'sports_esports',
    priceOptions: [9.99, 14.99, 17.99],
  },
  {
    id: 'nintendo-switch-online',
    label: 'Nintendo Switch Online',
    group: 'gaming',
    icon: 'stadia_controller',
    priceOptions: [3.99, 7.99, 19.99],
  },
  { id: 'gym', label: 'Gym', group: 'other', icon: 'fitness_center', priceOptions: [20, 35, 50] },
  { id: 'phone', label: 'Phone', group: 'other', icon: 'phone_iphone', priceOptions: [10, 20, 30] },
  { id: 'internet', label: 'Internet', group: 'other', icon: 'wifi', priceOptions: [25, 40, 60] },
  {
    id: 'insurance',
    label: 'Insurance',
    group: 'other',
    icon: 'health_and_safety',
    priceOptions: [15, 40, 80],
  },
  {
    id: 'custom',
    label: 'Other / Custom',
    group: 'other',
    icon: 'edit',
    priceOptions: [5, 10, 20],
  },
]
